/*autogenerated*/
import { imageAsset } from "../types";
export const imageStore: imageAsset[] = {
"0": {
  path: "../../res/img/cards/0.jpg",
  res: require('../../res/img/cards/0.jpg'),
},
"1": {
  path: "../../res/img/cards/1.jpg",
  res: require('../../res/img/cards/1.jpg'),
},
"10": {
  path: "../../res/img/cards/10.jpg",
  res: require('../../res/img/cards/10.jpg'),
},
"100": {
  path: "../../res/img/cards/100.jpg",
  res: require('../../res/img/cards/100.jpg'),
},
"101": {
  path: "../../res/img/cards/101.jpg",
  res: require('../../res/img/cards/101.jpg'),
},
"102": {
  path: "../../res/img/cards/102.jpg",
  res: require('../../res/img/cards/102.jpg'),
},
"103": {
  path: "../../res/img/cards/103.jpg",
  res: require('../../res/img/cards/103.jpg'),
},
"104": {
  path: "../../res/img/cards/104.jpg",
  res: require('../../res/img/cards/104.jpg'),
},
"105": {
  path: "../../res/img/cards/105.jpg",
  res: require('../../res/img/cards/105.jpg'),
},
"11": {
  path: "../../res/img/cards/11.jpg",
  res: require('../../res/img/cards/11.jpg'),
},
"12": {
  path: "../../res/img/cards/12.jpg",
  res: require('../../res/img/cards/12.jpg'),
},
"13": {
  path: "../../res/img/cards/13.jpg",
  res: require('../../res/img/cards/13.jpg'),
},
"14": {
  path: "../../res/img/cards/14.jpg",
  res: require('../../res/img/cards/14.jpg'),
},
"2": {
  path: "../../res/img/cards/2.jpg",
  res: require('../../res/img/cards/2.jpg'),
},
"3": {
  path: "../../res/img/cards/3.jpg",
  res: require('../../res/img/cards/3.jpg'),
},
"4": {
  path: "../../res/img/cards/4.jpg",
  res: require('../../res/img/cards/4.jpg'),
},
"bass": {
  path: "../../res/img/cards/bass.jpg",
  res: require('../../res/img/cards/bass.jpg'),
},
}
