import fs from "fs/promises";
const path = "res/img/cards";
const fullPath = `../../${path}`;

async function main() {
  console.log("/*autogenerated*/");
  console.log("import { imageAsset } from \"../types\";");
  console.log("export const imageStore: imageAsset[] = {");

  const files = await fs.readdir(path);
  for (const file of files) {
    console.log(`"${file.split(".")[0]}": {
  path: "${fullPath}/${file}",
  res: require('${fullPath}/${file}'),
},`);
  }

  console.log("}");
}

main();